services:
  - type: web
    name: sunass-informe-caracterizacion
    env: python
    buildCommand: pip install -r requirements.txt
    startCommand: gunicorn -c gunicorn_config.py dap_automate:app
    envVars:
      - key: PYTHON_VERSION
        value: 3.9.12
      - key: TENANT_ID
        sync: false
      - key: CLIENT_ID
        sync: false
      - key: CLIENT_SECRET
        sync: false
      - key: RESOURCE
        sync: false
      - key: DRIVE_ID
        sync: false 